// src/components/BookingForm/index.jsx
"use client";
import React, { useState, useEffect } from "react";
import TimePicker from "../TimePicker";
import { DatePicker } from "../DatePicker";
import styles from "./style.module.scss";
import { format } from "date-fns";
import { toast } from "sonner";

const BookingForm = () => {
	const [isBookingTime, setBookingTime] = useState(0);
	const [date, setDate] = React.useState();
	const [errors, setErrors] = useState({});
	const [hasBooked, setHasBooked] = useState(false);
	const [isFormData, setFormData] = useState({
		name: "",
		email: "",
		guests: "",
		phone: "",
		message: "",
		date: "",
		time: "",
	});
	useEffect(() => {
		setErrors({});
	}, [isFormData]);

	useEffect(() => {
		setFormData((prev) => ({
			...prev,
			date: date ? format(date, "yyyy-MM-dd") : "",
		}));
	}, [date]);

	const hasErrors = Object.keys(errors).length > 0;

	const handleSubmit = async (event) => {
		event.preventDefault();
		//check if isFormData has any empty fields, some = ifall vilken som helst av dom är tom.
		const hasEmptyField = Object.values(isFormData).some(
			(value) => String(value).trim() === ""
		);

		//hämta alla tomma fält
		const emptyFields = Object.entries(isFormData)
			.filter(([, value]) => String(value).trim() === "")
			.map(([key]) => key);

		//vi loopar igenom alla tomma fält, vi hämtar ut alla keys, och varje key får ett värde av true
		if (emptyFields.length) {
			const errorMap = emptyFields.reduce((acc, key) => {
				acc[key] = true;
				return acc;
			}, {});

			setErrors(errorMap);

			//vi stannar funktionen här
			return;
		}

		setErrors({});

		let responce = await fetch("/api/send", {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({
				name: isFormData.name,
				email: isFormData.email,
				guests: isFormData.guests,
				phone: isFormData.phone,
				message: isFormData.message,
				date: format(date, "yyyy-MM-dd"),
				time: isFormData.time,
			}),
		});

		const result = await responce.json();

		if (result.status === 200) {
			setHasBooked(true);
		}

		console.log("Responce", result);
	};

	return (
		<div className={styles.container}>
			<form
				onSubmit={handleSubmit}
				className="w-full h-full flex items-center justify-center"
			>
				<div className="  w-full ">
					<div className="flex flex-col gap-4 ea-grid ">
						<div className=" flex-1 flex flex-col flex-grow gap-4 ea-col-6 ea-col-xs-12 ">
							<input
								type="text"
								name="name"
								placeholder="Namn"
								onInput={() => setErrors({})}
								onChange={(e) =>
									setFormData({
										...isFormData,
										name: e.target.value,
									})
								}
								className={`bg-colorForm w-full py-2 px-4 rounded-md font-Inter text-[#5F6952] ${errors.name ? "border border-red-400" : "border"} border-input hover:border-[#5F6952]`}
							/>

							<input
								type="text"
								name="email"
								placeholder="Email"
								onChange={(e) =>
									setFormData({
										...isFormData,
										email: e.target.value,
									})
								}
								className={`bg-colorForm w-full py-2 px-4 rounded-md font-Inter text-[#5F6952] ${errors.email ? "border border-red-400" : "border"} border-input hover:border-[#5F6952]`}
							/>

							<div className="flex flex-col gap-4 justify-between md:flex-row">
								<div
									className={`rounded-md w-full cursor-pointer ${errors.guests ? "border border-red-400" : "border"} border-input flex justify-start`}
								>
									<select
										id="pet-select"
										name="guest"
										onChange={(e) =>
											setFormData({
												...isFormData,
												guests: e.target.value,
											})
										}
										className="p-2  h-12   text-[#9CA3B0] bg-white w-full"
									>
										<option value="">Antal gäster</option>
										<option value="1">1 Gäst</option>
										<option value="2">2 Gäster</option>
										<option value="3">3 Gäster</option>
										<option value="4">4 Gäster</option>
										<option value="5">5 Gäster</option>
										<option value="6">6 Gäster</option>
									</select>
								</div>
								<div>
									<DatePicker
										errors={errors}
										date={date}
										setDate={setDate}
									/>
								</div>
								<div>
									<TimePicker
										errors={errors}
										isFormData={isFormData}
										setFormData={setFormData}
									/>
								</div>
							</div>
						</div>
						<div className=" flex-1 flex-grow flex flex-col gap-4  ea-col-6 ea-col-xs-12 ">
							<input
								type="text"
								name="phone"
								placeholder="Telefonnummer"
								onChange={(e) =>
									setFormData({
										...isFormData,
										phone: e.target.value,
									})
								}
								className={`bg-colorForm w-full py-2 px-4 rounded-md font-Inter text-[#5F6952] ${errors.phone ? "border border-red-400" : "border"} border-input hover:border-[#5F6952]`}
							/>

							<textarea
								type="textarea"
								name="message"
								placeholder="Meddelande"
								onChange={(e) =>
									setFormData({
										...isFormData,
										message: e.target.value,
									})
								}
								className={`bg-colorForm w-full h-full resize-none py-2 px-4 rounded-md font-Inter text-[#5F6952] ${errors.message ? "border border-red-400" : "border"} border-input hover:border-[#5F6952]`}
							/>
						</div>
					</div>
					<div>
						<button
							className={`w-full bg-[#5F6952] py-4 rounded-md mt-4 text-white font-Inter ${hasErrors ? "animation-shake bg-red-400" : ""}`}
							disabled={hasBooked}
						>
							{hasErrors
								? "Alla fält måste vara ifyllda!"
								: hasBooked
									? "Tack för din bokning!"
									: "Boka bord"}
						</button>
					</div>
				</div>
			</form>
		</div>
	);
};

export default BookingForm;

// src/lib/components/BookingForm.svelte
<script>
	//stores
	import { formData, updateFormData } from "$lib/stores/bookingFormStore";
	import { language } from "$lib/stores/languageStore";

	//components
	import TimePicker from "./booking/TimePicker.svelte";
	import DatePicker from "./booking/DatePicker.svelte";
	import GuestSelect from "./booking/GuestSelect.svelte";

	//icons
	import UsersThree from "phosphor-svelte/lib/UsersThree";
	import CalendarDots from "phosphor-svelte/lib/CalendarDots";
	import Clock from "phosphor-svelte/lib/Clock";

	let errors = $state({});
	let hasBooked = $state(false);
	let currentLanguage = $state("sv");
	const t = (sv, en) => (currentLanguage === "en" ? en : sv);

	$effect(() => {
		currentLanguage = $language;
	});

	$effect(() => {
		$formData;
		errors = {};
	});

	function validate(data) {
		const next = {};
		const name = (data.name || "").trim();
		const email = (data.email || "").trim();
		const phone = (data.phone || "").trim();
		const guests = data.guests;
		const date = data.date;
		const time = data.time || {};

		if (!name) next.name = t("Namn är obligatoriskt.", "Name is required.");
		if (!email) next.email = t("Email är obligatoriskt.", "Email is required.");
		else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))
			next.email = t("Ange en giltig email.", "Enter a valid email.");

		if (!guests) next.guests = t("Välj antal gäster.", "Select number of guests.");
		if (!date) next.date = t("Välj datum.", "Select a date.");
		if (!time.hour || !time.minute) next.time = t("Välj tid.", "Select a time.");

		if (!phone) next.phone = t("Telefonnummer är obligatoriskt.", "Phone number is required.");
		else if (!/^[0-9+\-()\s]{6,}$/.test(phone))
			next.phone = t("Ange ett giltigt telefonnummer.", "Enter a valid phone number.");

		return next;
	}

	async function handleSubmit() {
		const nextErrors = validate($formData);
		errors = nextErrors;
		if (Object.keys(nextErrors).length > 0) return;

		// console.log("hehe");
		let response = await fetch("/api/send", {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({
				name: $formData.name,
				email: $formData.email,
				guests: $formData.guests,
				phone: $formData.phone,
				message: $formData.message,
				date: $formData.date,
				time: $formData.time,
				language: currentLanguage,
			}),
		});

		const result = await response.json();

		if (response.status === 200) {
			hasBooked = true;
		}

		console.log("Response", result);
	}
</script>

<div class="table-booking-form">
	<div class="d-flex flex-column">
		<div class="d-flex flex-column">
			<input
			onfocus={() => (errors = {})}
			oninput={(e) => updateFormData({ name: e.currentTarget.value })}
			type="text"
			placeholder={t("Namn", "Name")}
			class:error={errors.name}
		/>
			<input
				onfocus={() => (errors = {})}
			oninput={(e) =>
				updateFormData({ email: e.currentTarget.value })}
			type="text"
			placeholder={t("Email", "Email")}
			class:error={errors.email}
		/>
		</div>
		<div class="d-flex flex-column-xs">
			<div
				class="custom-component-input-container"
				class:error={errors.guests}
			>
				<GuestSelect />
				<UsersThree size={"1.25rem"} />
			</div>
			<div
				class="custom-component-input-container"
				class:error={errors.date}
			>
				<DatePicker />
				<CalendarDots size={"1.25rem"} />
			</div>
			<div
				class="custom-component-input-container"
				class:error={errors.time}
			>
				<TimePicker />
				<Clock size={"1.25rem"} />
			</div>
		</div>
	</div>
	<div class="d-flex flex-column">
		<input
			onfocus={() => (errors = {})}
			oninput={(e) => updateFormData({ phone: e.currentTarget.value })}
			type="text"
			placeholder={t("Telefonnummer", "Phone number")}
			class:error={errors.phone}
		/>
		<textarea
			onfocus={() => (errors = {})}
			oninput={(e) => updateFormData({ message: e.currentTarget.value })}
			placeholder={t("Meddelande", "Message")}
		></textarea>
	</div>
	<button
		class:error={Object.keys(errors).length > 0}
		onclick={handleSubmit}
		class="primary submit-button"
	>
		{#if hasBooked}
			<span class="submit-title">
				{t("Tack för din bokning", "Thank you for your booking")}
			</span>
		{:else if Object.keys(errors).length > 0}
			<span class="submit-title">
				{t("Dessa fält måste vara ifyllda", "These fields must be filled in")}
			</span>
		{:else}
			<span class="submit-title">{t("Boka bord", "Book a table")}</span>
		{/if}
	</button>
</div>

<style lang="scss">
	.table-booking-form {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 1rem;
		padding: 1rem;

		@media (max-width: 768px) {
			grid-template-columns: 1fr;
		}

		.d-flex {
			gap: 1rem;
		}
	}

	.submit-button {
		grid-column: span 2;

		&.error {
			background-color: rgb(228, 82, 82);
			animation: shake .7s ease-in-out;
		}

		@media (max-width: 768px) {
			grid-column: span 1;
		}
	}

	input.error,
	textarea.error,
	.custom-component-input-container.error {
		border: 1px solid rgb(228, 118, 118);
		box-shadow: 0 0 0 1px rgba(216, 141, 141, 0.11);
	}

	.submit-title {
		display: block;
	}

	.submit-note {
		display: block;
		font-size: 0.8rem;
		opacity: 0.85;
	}
</style>
